# Generated by Django 5.2.7 on 2025-10-31 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='type',
            field=models.CharField(choices=[('F', 'Fix'), ('C', 'Check'), ('R', 'Replace')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='note',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='technician_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='main_app.ticket'),
        ),
    ]
