# Generated by Django 5.2.7 on 2025-10-31 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_worklog_type_alter_worklog_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '😐'), (2, '🙂'), (3, '🤩')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main_app.ticket')),
            ],
        ),
    ]
